spring:
 profiles: prof1
 application:
    name: eureka-server
eureka:
 instance:
   preferIpAddress: true
   hostname: peer1
   metadataMap:
     zone: zone1
 client:
   registerWithEureka: true
   fetchRegistry: true 
   serviceUrl:
     defaultZone: http://localhost:8762/eureka/
     preferSameZoneEureka: true
server: 
 port: ${PORT:8761}